openapi: 3.1.0
info:
  title: Life Plan Agent
  description: Writes data to Google Sheets
  version: 1.0.0
servers:
  - url: https://life-plan-agent.vercel.app
paths:
  /api/write:
    post:
      operationId: writeToSheet
      summary: Write data to a Google Sheet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                spreadsheetId:
                  type: string
                range:
                  type: string
                values:
                  type: array
                  items:
                    type: array
                    items:
                      type: string
              required:
                - spreadsheetId
                - range
                - values
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  updatedRange:
                    type: string
        '500':
          description: Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
