openapi: 3.1.0
info:
  title: Google Sheets Agent
  version: 1.0.0
servers:
  - url: https://markbrown88.github.io/gpt-actions
paths:
  /read:
    get:
      operationId: readSheet
      summary: Read from a Google Sheet
      parameters:
        - name: spreadsheetId
          in: query
          required: true
          schema:
            type: string
        - name: range
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Returns the data from the sheet
  /write:
    post:
      operationId: writeSheet
      summary: Write to a Google Sheet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                spreadsheetId:
                  type: string
                range:
                  type: string
                values:
                  type: array
                  items:
                    type: array
                    items:
                      type: string
      responses:
        '200':
          description: Data written successfully
