openapi: 3.1.0
info:
  title: Life Plan Agent
  version: 1.0.0
  description: A custom GPT Action for writing to a Google Sheet to support life planning, tracking, and decision-making.

servers:
  - url: https://life-plan-agent.vercel.app

paths:
  /api/write:
    post:
      operationId: writeToSheet
      summary: Write data to a Google Sheet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                range:
                  type: string
                  description: The A1 notation of the range to update (e.g., "Sheet1!A1").
                values:
                  type: array
                  items:
                    type: array
                    items:
                      type: string
                  description: A 2D array of values to write to the sheet.
              required:
                - range
                - values
      responses:
        '200':
          description: Successful write to Google Sheet
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  updatedRange:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
