openapi: 3.1.0
info:
  title: Google Sheets Writer
  version: 1.0.0
paths:
  /api/write:
    post:
      operationId: writeToSheet
      summary: Write data to a Google Sheet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                spreadsheetId:
                  type: string
                range:
                  type: string
                values:
                  type: array
                  items:
                    type: array
                    items:
                      type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  updatedRange:
                    type: string
servers:
  - url: https://life-plan-agent.vercel.app
